### ISSUE TITLE
Are the purge paths correctly generated for liveblog objects

### ISSUE THREAD

**Issue by fredvd** [collective/collective.liveblog#16]
I'm not using liveblog actively, but was looking around for some code to generate purge paths for plone.cachepurging for content object

In caching/purge.py there are extra paths inserted using context.get_absolute_url(). Is this really what is meant, because plone.app.caching its default paths returned are all 'relative' paths from the Plone site object ("/plone/folder/myfile/view etc. ) and plone.cachepurging will probably add later add http://mysitename:80/ for all variants listed in the caching control panel "Front facing URL's" field.

**Comment by hvelarde** [comment]
sorry for the late answer: I have no idea; we've been using this for some months without problems but I don't remember if we are using the caching settings included in the package or not.

do you want me to check?

**Comment by fredvd** [comment]
Hii @hvelarde. No you don't need to check. It was just that when I dived into the purging functionality last year for another addon I spotted the code in liveblog and saw it was different in calculating urls. So if you would have issues this could be something to check. If it works fine its ok! :-)
