### ISSUE TITLE
Liveblog is slow when embedding many tweets

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.liveblog#29]
Twitter's strategy to embed tweets is broken by design: instead of using an `<iframe>` tag, every time a user inserts the code to embed a tweet, it inserts markup to load the widget script; here is an example of such code:

```html
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Nothing Twitter is doing is working <a href="https://t.co/s0FppnacwK">https://t.co/s0FppnacwK</a> <a href="https://t.co/GK9MRfQkYO">pic.twitter.com/GK9MRfQkYO</a></p>&mdash; The Verge (@verge) <a href="https://twitter.com/verge/status/725096763972001794">April 26, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
```

In the context of a Liveblog that means each tweet embedded tries to immediatly download another copy of the script, generating a useless request; it also means there is no easy way to lazy load the widget.

As an example, [this liveblog](http://www.brasil2016.gov.br/pt-br/coberturas-em-tempo-real/revezamento-da-tocha-brasilia) is loading more that 70 times the widget script, making the page really slow.

**Comment by rodfersou** [comment]
how about to add a view to provide this code into an iframe tag?

**Comment by hvelarde** [comment]
that's exactly what I was thinking; in fact Twitter offers an [oEmbed endpoint](https://dev.twitter.com/rest/reference/get/statuses/oembed).

we can get a JSON response using an URL like this: https://publish.twitter.com/oembed?url=https%3A%2F%2Ftwitter.com%2FInterior%2Fstatus%2F507185938620219395

the problem with this method is that we have no way to know the height of the `<iframe>`.

**Comment by hvelarde** [comment]
we will need to think more about this; a couple of resources to review later:

* https://dev.twitter.com/web/javascript/loading
* https://dev.twitter.com/web/javascript/initialization

**Comment by gbastien** [comment]
Hi,

Just reading github news, maybe https://github.com/collective/collective.js.iframeresizer could help you regarding the iframe height problem.

Gauthier

**Comment by rodfersou** [comment]
For local iframe I can resize with some javascript (like did in collective.behavior.featuredimage preview)

**Comment by rodfersou** [comment]
it will be fixed in https://github.com/collective/collective.lazysizes/issues/15

**Comment by hvelarde** [comment]
We will need to document the usage of collective.lazysizes with collective.liveblog.
