### ISSUE TITLE
Wrong author name on micro-update view

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.liveblog#30]
I was not able to reproduce this problem isolated but it's happening in production in two different sites:

![selection_066](https://cloud.githubusercontent.com/assets/341393/15164409/de73cae6-16e4-11e6-9801-837ba7d08d20.png)

![selection_067](https://cloud.githubusercontent.com/assets/341393/15164408/de73d9fa-16e4-11e6-8edc-d6a2fcb3b0a9.png)

The author's name is only visible to authenticated users.

**Comment by rodfersou** [comment]
maybe the problem is that these sites don't have chameleon installed.. we can change the ${author} into something like <span tal:replace="author" /> to avoid the problem

**Comment by hvelarde** [comment]
those sites have Chameleon installed, indeed.

**Comment by rodfersou** [comment]
I couldn't find where this problem happen
