### ISSUE TITLE
Spinner is duplicated in the liveblog

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.liveblog#35]
A second spinner is shown in the liveblog view:

![selection_073](https://cloud.githubusercontent.com/assets/341393/18054932/50c44028-6ddc-11e6-9e7b-79a042215343.png)

This is probably by a collision in the spinner id or class name.

**Comment by rodfersou** [comment]
Spinner should be removed from Plone 4.3.x since the event ajaxStart already shows a spinner:

https://github.com/plone/Products.CMFPlone/blob/4.3.x/Products/CMFPlone/skins/plone_ecmascript/kss-bbb.js#L51

What don't happen on Plone 5.x

**Comment by hvelarde** [comment]
the code you're referring is there just for backwards compatibility.

**Comment by rodfersou** [comment]
@hvelarde but this is the code that makes the spinner show when there is any ajax (what happen in liveblog, and duplicates the spinner)
